name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server/config.ini:/config.ini:ro
    networks:
      - testing_net
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NAME=name1
      - SURNAME=surname1
      - DOCUMENT=40000001
      - BIRTHDATE=2003-08-25
      - NUMBER=1001
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server
  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - NAME=name2
      - SURNAME=surname2
      - DOCUMENT=40000002
      - BIRTHDATE=2003-08-25
      - NUMBER=1002
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server
  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - NAME=name3
      - SURNAME=surname3
      - DOCUMENT=40000003
      - BIRTHDATE=2003-08-25
      - NUMBER=1003
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server
  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - NAME=name4
      - SURNAME=surname4
      - DOCUMENT=40000004
      - BIRTHDATE=2003-08-25
      - NUMBER=1004
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
